name: dailyRun

on:
  schedule:
    - cron: '*/2 * * * *'  # 4 PM Indonesia time is 9 AM UTC
  workflow_dispatch:  # Allow manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'  # or whatever version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          # Auto-load variables from .env manually if needed
          DB_URL: ${{ secrets.DB_URL }}
          DB_KEY: ${{ secrets.DB_KEY }}
        run: |
          python main.py
