name: afterDailyRun

on:
  workflow_run:
    workflows: ["dailyRun"] # Must match the 'name' in daily-run.yaml
    types:
      - completed
  workflow_dispatch: # Allow manual trigger too

jobs:
  run-after:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if dailyRun succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script2.py
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_KEY: ${{ secrets.DB_KEY }}
        run: |
          python calculateAccuracy.py
